language: python
python:
  - "3.6"
# 使用的服务，必要的数据库服务
services:
  - mysql
env:
  global:
    -TRAVIS=true
    - DJANGO=2.1.7
# command to install dependencies
before_install:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - mysql -e 'DROP DATABASE IF EXISTS transportation;' 
  - mysql -e 'CREATE DATABASE IF NOT EXISTS transportation;'
  - mysql -u root --default-character-set=utf8mb4 transportation < transportation.sql
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install python3 redis memcached;
      virtualenv -p python3 ~/py-env;
      . ~/py-env/bin/activate;
    fi

install:
  - pip install -r requirements.txt --use-mirrors
#  - pip install boxx/
# command to run tests
script: 
  - python manage.py test

