language: python
python:
  - "3.6"

# command to install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install python3 redis memcached;
      virtualenv -p python3 ~/py-env;
      . ~/py-env/bin/activate;
    fi

install:
  - pip install -r requirements.txt
#  - pip install boxx/
# command to run tests
script: 
  - python test.py

